In [ ]:
# Checking imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

print("pandas version:", pd.__version__)
print("numpy version:", np.__version__)
print("sklearn version:", sklearn.__version__)

pandas version: 2.2.2
numpy version: 2.0.2
sklearn version: 1.6.1

In [ ]:
# Dataset upload
from google.colab import files
uploaded = files.upload()

Saving pokemon.csv to pokemon.csv

In [ ]:
# Dataset load
import pandas as pd
df = pd.read_csv('pokemon.csv')
df.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

In [ ]:
# Basic checks
df.shape

(801, 41)

In [ ]:
# Basic checks
df.columns

Index(['abilities', 'against_bug', 'against_dark', 'against_dragon',
       'against_electric', 'against_fairy', 'against_fight', 'against_fire',
       'against_flying', 'against_ghost', 'against_grass', 'against_ground',
       'against_ice', 'against_normal', 'against_poison', 'against_psychic',
       'against_rock', 'against_steel', 'against_water', 'attack',
       'base_egg_steps', 'base_happiness', 'base_total', 'capture_rate',
       'classfication', 'defense', 'experience_growth', 'height_m', 'hp',
       'japanese_name', 'name', 'percentage_male', 'pokedex_number',
       'sp_attack', 'sp_defense', 'speed', 'type1', 'type2', 'weight_kg',
       'generation', 'is_legendary'],
      dtype='object')

In [ ]:
# Basic checks
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   abilities          801 non-null    object
 1   against_bug        801 non-null    float64
 2   against_dark       801 non-null    float64
 3   against_dragon     801 non-null    float64
 4   against_electric   801 non-null    float64
 5   against_fairy      801 non-null    float64
 6   against_fight      801 non-null    float64
 7   against_fire       801 non-null    float64
 8   against_flying     801 non-null    float64
 9   against_ghost      801 non-null    float64
 10  against_grass      801 non-null    float64
 11  against_ground     801 non-null    float64
 12  against_ice        801 non-null    float64
 13  against_normal     801 non-null    float64
 14  against_poison     801 non-null    float64
 15  against_psychic    801 non-null    float64
 16  against_rock       801 non-null    float64
 17  against_steel      801 non-null    float64
 18  against_water      801 non-null    float64
 19  attack             801 non-null    int64
 20  base_egg_steps     801 non-null    int64
 21  base_happiness     801 non-null    int64
 22  base_total         801 non-null    int64
 23  capture_rate       801 non-null    object
 24  classfication      801 non-null    object
 25  defense            801 non-null    int64
 26  experience_growth  801 non-null    int64
 27  height_m           781 non-null    float64
 28  hp                 801 non-null    int64
 29  japanese_name      801 non-null    object
 30  name               801 non-null    object
 31  percentage_male    703 non-null    float64
 32  pokedex_number     801 non-null    int64
 33  sp_attack          801 non-null    int64
 34  sp_defense         801 non-null    int64
 35  speed              801 non-null    int64
 36  type1              801 non-null    object
 37  type2              417 non-null    object
 38  weight_kg          781 non-null    float64
 39  generation         801 non-null    int64
 40  is_legendary       801 non-null    int64
dtypes: float64(21), int64(13), object(7)
memory usage: 256.7+ KB

In [ ]:
# Feature selections
df = df[['name','hp','attack','defense','sp_attack','sp_defense','speed','type1','is_legendary']]
df.head()

,name,hp,attack,defense,sp_attack,sp_defense,speed,type1,is_legendary
0,Bulbasaur,45,49,49,65,65,45,grass,0
1,Ivysaur,60,62,63,80,80,60,grass,0
2,Venusaur,80,100,123,122,120,80,grass,0
3,Charmander,39,52,43,60,50,65,fire,0
4,Charmeleon,58,64,58,80,65,80,fire,0

In [ ]:
# Checking missing values
df.isnull().sum()

name            0
hp              0
attack          0
defense         0
sp_attack       0
sp_defense      0
speed           0
type1           0
is_legendary    0
dtype: int64

In [ ]:
# Check duplicates
df.duplicated().sum()

np.int64(0)

In [ ]:
# Check data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          801 non-null    object
 1   hp            801 non-null    int64
 2   attack        801 non-null    int64
 3   defense       801 non-null    int64
 4   sp_attack     801 non-null    int64
 5   sp_defense    801 non-null    int64
 6   speed         801 non-null    int64
 7   type1         801 non-null    object
 8   is_legendary  801 non-null    int64
dtypes: int64(7), object(2)
memory usage: 56.4+ KB

In [ ]:
# Assigning battle style categories
def get_battle_style(row):
    if row['attack'] > 100 and row['speed'] > 80:
        return "Offensive"
    elif row['defense'] > 100 and row['hp'] > 80:
        return "Defensive"
    elif row['speed'] > 100:
        return "Speedster"
    elif row['sp_attack'] > 100:
        return "Special Attacker"
    else:
        return "Balanced"
df['battle_style'] = df.apply(get_battle_style, axis=1)
df.head()

,name,hp,attack,defense,sp_attack,sp_defense,speed,type1,is_legendary,battle_style
0,Bulbasaur,45,49,49,65,65,45,grass,0,Balanced
1,Ivysaur,60,62,63,80,80,60,grass,0,Balanced
2,Venusaur,80,100,123,122,120,80,grass,0,Special Attacker
3,Charmander,39,52,43,60,50,65,fire,0,Balanced
4,Charmeleon,58,64,58,80,65,80,fire,0,Balanced

In [ ]:
# Check overall distribution
df['battle_style'].value_counts()

battle_style
Balanced            571
Offensive            77
Special Attacker     61
Speedster            60
Defensive            32
Name: count, dtype: int64

In [ ]:
# X (input features) & Y (target)
X = df[['hp','attack','defense','sp_attack','sp_defense','speed']]
y = df['battle_style']

In [ ]:
# Assigning numerical values to categorical target variables
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
# Train-Test Split (80% training & 20% testing)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
# Scaling for KNN
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
# Import KNN > Create Model > Train Model
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5) # Training dataset with k=5 neighbors
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
# Prediction
y_pred = knn.predict(X_test)

In [ ]:
# Accuracy check
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8881987577639752

In [ ]:
# Precision, Recall and F1-Score
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.99      0.95       111
           1       1.00      0.30      0.46        10
           2       1.00      0.69      0.81        16
           3       0.64      1.00      0.78         9
           4       0.83      0.67      0.74        15

    accuracy                           0.89       161
   macro avg       0.88      0.73      0.75       161
weighted avg       0.90      0.89      0.88       161

In [ ]:
# User input function
def predict_style(user_input):
    user_df = pd.DataFrame([user_input])
    user_scaled = scaler.transform(user_df)
    pred = knn.predict(user_scaled)
    return le.inverse_transform(pred)[0]

In [ ]:
# Pokemon recommendation function
import numpy as np
def recommend_pokemon(user_input, top_n=3):
    # Step 1: predict battle style
    style = predict_style(user_input)
    # Step 2: filter same style Pokémon
    filtered = df[df['battle_style'] == style].copy()
    # Step 3: calculate distance from user input
    feature_cols = ['hp', 'attack', 'defense', 'sp_attack', 'sp_defense', 'speed']
    def calc_distance(row):
        return np.sqrt(
            (row['hp'] - user_input['hp'])**2 +
            (row['attack'] - user_input['attack'])**2 +
            (row['defense'] - user_input['defense'])**2 +
            (row['sp_attack'] - user_input['sp_attack'])**2 +
            (row['sp_defense'] - user_input['sp_defense'])**2 +
            (row['speed'] - user_input['speed'])**2
        )
    filtered['distance'] = filtered.apply(calc_distance, axis=1)
    # Step 4: sort by nearest distance
    filtered = filtered.sort_values(by='distance')
    # Step 5: return top matches
    return style, filtered[['name', 'type1', 'hp', 'attack', 'defense', 'sp_attack', 'sp_defense', 'speed', 'distance']].head(top_n)

In [ ]:
# Test system
user = {
    'hp': 70,
    'attack': 90,
    'defense': 60,
    'sp_attack': 85,
    'sp_defense': 60,
    'speed': 100
}
style, recs = recommend_pokemon(user)
print("Predicted Style:", style)
print("\nRecommended Pokémon:")
print(recs)

Predicted Style: Speedster

Recommended Pokémon:
         name  type1  hp  attack  defense  sp_attack  sp_defense  speed  \
513  Simisear   fire  75      98       63         98          63    101
515  Simipour  water  75      98       63         98          63    101
511  Simisage  grass  75      98       63         98          63    101

      distance
513  16.643317
515  16.643317
511  16.643317

In [ ]:
# Saving the model components
import joblib
joblib.dump(knn, 'knn_model.pkl')
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(le, 'label_encoder.pkl')
df.to_csv('pokemon_final.csv', index=False)
print("Files saved successfully")

# Download the model components
from google.colab import files
files.download('knn_model.pkl')
files.download('scaler.pkl')
files.download('label_encoder.pkl')
files.download('pokemon_final.csv')

Files saved successfully